# Use an official Nginx image as the base
FROM nginx:alpine

# Copy the "index.html" into the default Nginx static files directory
COPY index.html /usr/share/nginx/html/

# Expose port 80 to access the website
EXPOSE 80

